---
language: node_js
node_js:
  - "7"

sudo: false

cache:
  yarn: true

install:
  - yarn install
  - bower install

before_script: 
    - openssl aes-256-cbc -d -in key.pem.enc -out key.pem -k $ENC_KEY

script:
  - bash ./deployToProduction.sh
